name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Set up NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install the Angular CLI
      run: |
        npm install -g @angular/cli

    - name: Install Typescript dependencies
      run: |
        cd frontend && npm install

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PWD
        echo $PYTHONPATH

    - name: Lint Python code with flake8
      run: |
        flake8 `find backend ! -path "*migrations*" -name "*.py"`

    - name: Lint Typescript code with ESLint
      run: |
        cd frontend && ng lint

    - name: Run backend Django test cases
      run: |
        echo $PWD
        python manage.py test

    #- name: Run frontend Angular test cases
    #  run: |
    #    cd frontend && ng test
